### ISSUE TITLE
Attacks module doesn't work

### ISSUE THREAD

**Issue by gatewaynode** [gatewaynode/smurf#13]
(smurf) foo@bar:~/Code/smurf$ ./smurf.py -u localhost -s 1
[+] b'URL: http://localhost'
[+] b'Starting: 25/11/2018 at 18:06:05'

[i] b'Starting attacks module...'
[i] b'Checking OS Command Injection...'
Traceback (most recent call last):
  File "./smurf.py", line 120, in <module>
    wascan().main()
  File "./smurf.py", line 93, in main
    Attacks(kwargs,url,kwargs['data'])
  File "/home/mobile/Code/smurf/lib/handler/attacks.py", line 24, in Attacks
    module(kwargs,url,data).run()
  File "/home/mobile/Code/smurf/plugins/attacks/oscommand.py", line 48, in run
    for url in urls.run():
  File "/home/mobile/Code/smurf/lib/utils/params.py", line 75, in run
    self.get()
  File "/home/mobile/Code/smurf/lib/utils/params.py", line 55, in get
    params = self.url.split("?")[1].split("&")
IndexError: list index out of range

**Comment by gatewaynode** [comment]
Most of these bugs seemed to be around interacting with clean URLs and no query string.

The attack functionality doesn't throw any errors now, but I haven't verified that it really works yet.  This is going to be a big target of refactoring as there is a ton of potential to break lot's of code off into some simple classes.

Putting off the verification of functionality until after Python 3 migration and Cement implementation.
