### ISSUE TITLE
Audit doesn't work

### ISSUE THREAD

**Issue by gatewaynode** [gatewaynode/smurf#17]
[+] b'URL: http://localhost'
[+] b'Starting: 26/11/2018 at 18:56:53'

[i] b'Starting audit module...'
[i] b'Checking Open Redirect..'
Traceback (most recent call last):
  File "./smurf.py", line 120, in <module>
    wascan().main()
  File "./smurf.py", line 95, in main
    Audit(kwargs,url,kwargs['data'])
  File "/home/mobile/Code/smurf/lib/handler/audit.py", line 26, in Audit
    module(kwargs,url,data).run()
  File "/home/mobile/Code/smurf/plugins/audit/open_redirect.py", line 35, in run
    url = CPath(self.url,'/')+path
TypeError: must be str, not bytes

**Comment by gatewaynode** [comment]
More byte and string disparities.  So many opportunities for refactoring/enhancing in the future.
